trigger:
- main

variables:
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: MyAgentPool
    steps:
    - script: |
        echo "Installing Maven"
        wget https://archive.apache.org/dist/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
        sudo tar xf apache-maven-3.9.8-bin.tar.gz -C /opt
        sudo ln -s /opt/apache-maven-3.9.8 /opt/maven
        echo 'export MAVEN_HOME=/opt/maven' | sudo tee -a /etc/profile.d/maven.sh
        echo 'export PATH=${MAVEN_HOME}/bin:${PATH}' | sudo tee -a /etc/profile.d/maven.sh
        sudo chmod +x /etc/profile.d/maven.sh
        source /etc/profile.d/maven.sh
      displayName: 'Install Maven'

    - script: |
        echo "Checking Maven Installation"
        mvn -version
      displayName: 'Check Maven Installation'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: $(rootFolder)
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: dev
    variables:
    - group: Release
    pool:
      name: MyAgentPool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy'
            inputs:
              azureSubscription: 'resource manager spring-framework-petclinic'
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
