# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'a3d3dcd1-f762-469c-8963-ecea86e6d10e'

  # Web app name
  webAppName: 'spring-framework-petclinic-32333'

  # Environment name
  environmentName: 'spring-framework-petclinic-32333'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: MyAgentPool1

    steps:
    - task: Bash@3
      displayName: 'set up maven enviroment'
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-18-openjdk-amd64" && \
          echo "##vso[task.setvariable variable=M2_HOME]/usr/share/maven" && \
          echo "##vso[task.setvariable variable=MAVEN_HOME]/usr/share/maven" && \
          echo "##vso[task.setvariable variable=PATH]$PATH:/usr/share/maven/bin"
    - task: Bash@3
      displayName: 'Add maven to PATH and verify'
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=PATH]$(M2_HOME)/bin:$(PATH)"
          mvn -v

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      name: MyAgentPool1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: spring-framework-petclinic-32333'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
