trigger:
- main

variables:
  rootFolder: $(System.DefaultWorkingDirectory)
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: MyAgentPool
    steps:
    - script: |
        echo "Setting up Maven environment"
        export MAVEN_HOME=/opt/maven
        export PATH=$MAVEN_HOME/bin:$PATH
        echo "Maven Home: $MAVEN_HOME"
        echo "Path: $PATH"
      displayName: 'Setup Maven Environment'
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: $(rootFolder)
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: dev
    variables:
    - group: Release
    pool:
      name: MyAgentPool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy'
            inputs:
              azureSubscription: 'resource manager spring-framework-petclinic'
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
